os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc

    - channel: nightly
      target: x86_64-pc-windows-msvc
  
  global:
    PGUSER: postgres
    PGPASSWORD: Password12!
    DATABASE_URL: postgres://postgres:Password12!@localhost/attendance_management

matrix:
  allow_failures:
    - channel: nightly

services:
  - postgresql95

cache:
  - C:\Users\appveyor\.cargo

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%
  - SET PATH=C:\Program Files\PostgreSQL\9.5\bin;%PATH%
  - cargo install diesel_cli --no-default-features --features=postgres --force

before_test:
  - diesel setup
  - diesel migration run
  
build: false

test_script:
  - cargo test --verbose
