language: rust

rust:
  - nightly
  - stable

services:
  - postgresql

before_script:
  - cargo install diesel_cli --no-default-features --features=postgres --force
  - diesel setup
  - diesel migration run

script:
  - cargo test --verbose --all

cache: cargo


env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/attendance_management
