language: rust

rust:
  - nightly
  - stable

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - cargo install diesel_cli --no-default-features --features=postgres --force
  - diesel migration --migration-dir test_migrations --database-url postgres://postgres@localhost/test_db run

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

cache: cargo

after_script:
  - diesel migration --migration-dir test_migrations --database-url postgres://postgres@localhost/test_db revert

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/test_db
