[package]
name = "attendance-rs"
version = "0.1.0"
authors = ["Akhil kp <akhilkpdasan@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
serde = "*"
serde_json = "*"
serde_derive = "*"
actix = "*"
actix-web = "*"
futures = "*"
bytes = "*"
